'use client';

import { useState } from 'react';
import Link from 'next/link';

interface FAQItem {
  question: string;
  answer: string | React.ReactNode;
}

const faqs: FAQItem[] = [
  {
    question: 'What is MeritView?',
    answer: 'MeritView is an AI-powered decision support platform that analyzes contract disputes. For a flat $49 fee, we provide a structured, multi-model analysis of your dispute\'s strengths and weaknesses. MeritView is not a replacement for legal advice.'
  },
  {
    question: 'How does MeritView work?',
    answer: 'You fill out a structured 5-section brief describing your dispute, submit it with the $49 fee, and our system dispatches your brief to three leading AI models (Llama 3 70B, Mixtral 8x7B, and Gemini 1.5 Pro). Each model independently evaluates your case and produces a structured opinion, which is then aggregated into a clear report.'
  },
  {
    question: 'How much does it cost?',
    answer: 'MeritView costs a flat $49 USD per analysis. There are no hidden fees, subscriptions, or additional charges. This includes analysis by all three AI models and the aggregated opinion.'
  },
  {
    question: 'Is MeritView legal advice?',
    answer: 'No. MeritView provides decision support, not legal advice. Our analysis is generated by AI models and is intended to help you understand your position and make informed decisions. You should always consult a qualified attorney for legal advice specific to your situation.'
  },
  {
    question: 'Who should use MeritView?',
    answer: 'MeritView is designed for individuals and small businesses involved in contract disputes who want an affordable, structured analysis of their position. It is ideal for disputes where the stakes may not justify the cost of traditional legal consultation.'
  },
  {
    question: 'What types of disputes does MeritView handle?',
    answer: 'Currently, MeritView handles contract interpretation disputes. This includes disputes about the meaning of contract terms, whether certain obligations were triggered, and whether a party\'s actions aligned with contractual requirements.'
  },
  {
    question: 'How long does the analysis take?',
    answer: 'Most analyses are completed within hours of submission. The three AI models evaluate your brief independently, and once all three evaluations are received, the aggregated opinion is generated. In rare cases of high demand, it may take up to 24 hours.'
  },
  {
    question: 'How do I submit my dispute?',
    answer: 'Create a free account, complete the structured 5-section brief form, pay the $49 fee, and submit. The process is guided and typically takes about 30 minutes to complete the brief.'
  },
  {
    question: 'What information do I need to provide?',
    answer: 'You will need to provide a factual background of the dispute, your position and interpretation of the contract, supporting arguments, acknowledgment of the opposing party\'s arguments, and your desired resolution. The form guides you through each section.'
  },
  {
    question: 'Is my information kept confidential?',
    answer: 'Yes. Your brief content is encrypted at rest using AES-256-GCM encryption and in transit using TLS. We never train AI models on your data or share your information with third parties. See our Privacy Policy for details.'
  },
  {
    question: 'Can I edit my brief after submission?',
    answer: 'No. Once a brief is submitted, it is sealed and cannot be edited. This ensures the integrity of the analysis. You can save drafts before submission, and we recommend reviewing your brief carefully before submitting.'
  },
  {
    question: 'What AI models are used?',
    answer: 'We use three leading AI models: Meta\'s Llama 3 70B (via Groq), Mistral\'s Mixtral 8x7B (via Groq), and Google\'s Gemini 1.5 Pro. These models were selected for their strong reasoning capabilities and support for structured JSON output.'
  },
  {
    question: 'How do you ensure the quality of AI analysis?',
    answer: 'We use multiple independent AI models to reduce individual model bias, enforce structured JSON output schemas, validate outputs for consistency and injection attacks, and record prompt versions for reproducibility. Each evaluation is independently generated.'
  },
  {
    question: 'What does the opinion report include?',
    answer: 'The opinion report includes: an executive summary, your strongest and weakest arguments identified, factual concerns and gaps flagged, confidence scores for each assessment, logical fallacy analysis, and a PDF export option.'
  },
  {
    question: 'Can I get a refund?',
    answer: 'If fewer than three AI models successfully evaluate your brief, you will receive an automatic refund. You may also request a refund within 7 days if the analysis does not meet your expectations, subject to our refund policy.'
  },
  {
    question: 'Is MeritView available internationally?',
    answer: 'MeritView is currently available in jurisdictions where AI-based decision support tools are permitted. We may restrict access in certain jurisdictions based on local regulations. Check our Terms of Service for more information.'
  },
  {
    question: 'Do I need to create an account?',
    answer: 'Yes, you need a free account to submit disputes and access your analysis. Registration requires your email address and a password. Your account stores your dispute history and analysis results.'
  },
  {
    question: 'How do I export my analysis?',
    answer: 'Each analysis report can be downloaded as a PDF from the opinion delivery page. The PDF includes the complete analysis, disclaimers, timestamps, and information about which AI models were used.'
  },
  {
    question: 'What happens if an AI model fails?',
    answer: 'Our system automatically retries failed evaluations up to three times. If a model continues to fail, the analysis proceeds with the successful evaluations. If fewer than three models succeed, you receive an automatic refund.'
  },
  {
    question: 'Is there a word limit for the brief?',
    answer: 'The brief has a suggested length of 500-2000 words total across all five sections, with a hard cap of 5000 words. Each section must contain at least some content for the brief to be submitted.'
  },
  {
    question: 'How do I contact support?',
    answer: 'You can reach us at support@meritview.com. We aim to respond to all inquiries within 24 hours on business days.'
  },
  {
    question: 'Can I use MeritView for disputes outside the US?',
    answer: 'Yes, MeritView can analyze contract disputes governed by laws of any jurisdiction. However, the AI models provide analysis based on general contract principles and may not be familiar with specific local laws.'
  },
  {
    question: 'What is a seal hash?',
    answer: 'A seal hash is a SHA-256 cryptographic hash of your encrypted brief content. It serves as proof that your brief has not been altered since submission. You can verify the integrity of your brief using this hash.'
  },
  {
    question: 'Does MeritView use my data for training?',
    answer: 'No. We never use your dispute data to train AI models or improve AI systems. Your data remains yours. See our Privacy Policy for detailed information about data handling.'
  },
  {
    question: 'What payment methods are accepted?',
    answer: 'We accept all major credit and debit cards through our secure Stripe payment processing. All payments are processed in USD.'
  },
];

function AccordionItem({ faq, isOpen, onToggle }: { faq: FAQItem; isOpen: boolean; onToggle: () => void }) {
  return (
    <div className="border border-border rounded-lg overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between px-6 py-4 text-left bg-card hover:bg-accent/50 transition-colors"
        aria-expanded={isOpen}
      >
        <span className="font-medium text-sm md:text-base pr-4">{faq.question}</span>
        <svg
          className={`w-5 h-5 shrink-0 text-muted-foreground transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      <div
        className={`overflow-hidden transition-all duration-200 ${isOpen ? 'max-h-96' : 'max-h-0'}`}
        role="region"
        aria-hidden={!isOpen}
      >
        <div className="px-6 pb-4 text-sm text-muted-foreground leading-relaxed">
          {faq.answer}
        </div>
      </div>
    </div>
  );
}

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div className="container px-4 py-16 space-y-8">
      <section className="max-w-3xl mx-auto text-center space-y-6">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight">
          Frequently Asked Questions
        </h1>
        <p className="text-xl text-muted-foreground">
          Everything you need to know about MeritView. Can&apos;t find what you&apos;re looking for?{' '}
          <a href="mailto:support@meritview.com" className="text-primary hover:underline">
            Contact us
          </a>.
        </p>
      </section>

      <div className="max-w-3xl mx-auto space-y-3">
        {faqs.map((faq, index) => (
          <AccordionItem
            key={index}
            faq={faq}
            isOpen={openIndex === index}
            onToggle={() => setOpenIndex(openIndex === index ? null : index)}
          />
        ))}
      </div>

      <section className="max-w-3xl mx-auto text-center space-y-4 bg-muted/50 p-8 rounded-xl mt-12">
        <h2 className="text-2xl font-bold">Still Have Questions?</h2>
        <p className="text-muted-foreground">
          We are happy to help. Reach out to our team and we will get back to you within 24 hours.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <a
            href="mailto:support@meritview.com"
            className="rounded-md bg-primary px-6 py-2.5 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors"
          >
            Email Support
          </a>
          <Link
            href="/register"
            className="rounded-md border border-border px-6 py-2.5 text-sm font-medium hover:bg-accent transition-colors"
          >
            Create Account
          </Link>
        </div>
      </section>
    </div>
  );
}
