'use client';

import { useParams } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '@/lib/api-client';
import { Button } from '@/components/ui/button';

interface OpinionEvaluator {
  provider_name: string;
  confidence: number;
}

interface OpinionData {
  id: string;
  dispute_id: string;
  content: string;
  inter_evaluator_agreement: number;
  overall_confidence: number;
  generated_at: string;
  evaluators: OpinionEvaluator[];
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

function confidenceColor(value: number): string {
  if (value >= 0.8) return 'text-green-600';
  if (value >= 0.6) return 'text-yellow-600';
  return 'text-red-600';
}

function agreementLabel(value: number): string {
  if (value >= 0.9) return 'Very High';
  if (value >= 0.8) return 'High';
  if (value >= 0.7) return 'Moderate';
  if (value >= 0.6) return 'Fair';
  return 'Low';
}

const DISCLAIMER = 'This opinion is generated by AI and is provided for informational purposes only. It does not constitute legal advice. You should consult with a qualified attorney for legal advice specific to your situation.';

export default function OpinionPage() {
  const params = useParams();
  const disputeId = params.id as string;

  const opinionQuery = useQuery<OpinionData>({
    queryKey: ['opinion', disputeId],
    queryFn: () => apiClient.get<OpinionData>(`/disputes/${disputeId}/opinion`),
    enabled: !!disputeId,
  });

  const handleDownloadPdf = async () => {
    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api/v1'}/disputes/${disputeId}/opinion/pdf`,
        {
          headers: {
            Authorization: `Bearer ${localStorage.getItem('auth-storage') ? JSON.parse(localStorage.getItem('auth-storage')!).state?.accessToken : ''}`,
          },
        }
      );
      if (!response.ok) throw new Error('Download failed');
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `opinion-${disputeId}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('PDF download error:', err);
    }
  };

  const isLoading = opinionQuery.isLoading;
  const isError = opinionQuery.isError;

  if (isLoading) {
    return (
      <div className="max-w-3xl mx-auto space-y-4 animate-fade-in">
        <div className="h-8 w-64 bg-slate-200 rounded animate-pulse" />
        <div className="h-4 w-96 bg-slate-200 rounded animate-pulse" />
        <div className="h-64 w-full bg-slate-200 rounded animate-pulse" />
        <div className="h-32 w-full bg-slate-200 rounded animate-pulse" />
      </div>
    );
  }

  if (isError) {
    return (
      <div className="text-center py-12 animate-fade-in">
        <p className="text-red-600 mb-4">
          {opinionQuery.error instanceof Error ? opinionQuery.error.message : 'Failed to load opinion.'}
        </p>
        <Button variant="outline" onClick={() => opinionQuery.refetch()}>
          Try Again
        </Button>
      </div>
    );
  }

  if (!opinionQuery.data) {
    return (
      <div className="text-center py-12 animate-fade-in">
        <p className="text-slate-500">No opinion found for this dispute.</p>
      </div>
    );
  }

  const opinion = opinionQuery.data;

  return (
    <div className="max-w-3xl mx-auto space-y-6 animate-fade-in">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Opinion</h1>
        <Button variant="outline" onClick={handleDownloadPdf}>
          Download PDF
        </Button>
      </div>

      <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 text-sm text-yellow-800">
        {DISCLAIMER}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="border rounded-lg p-4">
          <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Inter-Evaluator Agreement</p>
          <p className={`text-lg font-bold ${confidenceColor(opinion.inter_evaluator_agreement)}`}>
            {agreementLabel(opinion.inter_evaluator_agreement)} ({(opinion.inter_evaluator_agreement * 100).toFixed(0)}%)
          </p>
        </div>
        <div className="border rounded-lg p-4">
          <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Overall Confidence</p>
          <p className={`text-lg font-bold ${confidenceColor(opinion.overall_confidence)}`}>
            {(opinion.overall_confidence * 100).toFixed(0)}%
          </p>
        </div>
        <div className="border rounded-lg p-4">
          <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">Generated</p>
          <p className="text-lg font-bold text-slate-900">{formatDate(opinion.generated_at)}</p>
        </div>
      </div>

      {opinion.evaluators.length > 0 && (
        <div className="border rounded-lg p-4">
          <p className="text-xs text-slate-500 uppercase tracking-wide mb-2">Evaluators Used</p>
          <div className="flex flex-wrap gap-2">
            {opinion.evaluators.map((e, i) => (
              <span key={i} className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-slate-100 text-xs font-medium text-slate-700">
                {e.provider_name}
                <span className="text-slate-400">({(e.confidence * 100).toFixed(0)}%)</span>
              </span>
            ))}
          </div>
        </div>
      )}

      <div className="border rounded-lg p-6 bg-white">
        <div className="prose prose-slate max-w-none whitespace-pre-wrap text-sm leading-relaxed">
          {opinion.content}
        </div>
      </div>

      <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 text-sm text-yellow-800">
        {DISCLAIMER}
      </div>
    </div>
  );
}
