import PDFDocument from 'pdfkit';
import { prisma } from '../../db/prisma';
import { decrypt } from '../../utils/crypto';
import { logger } from '../../utils/logger';
import { InternalError, NotFoundError } from '../../utils/errors';
import path from 'path';
import fs from 'fs';
import os from 'os';

const PDF_DIR = path.join(os.tmpdir(), 'meritview-uploads');

export async function generateOpinionPdf(disputeId: string): Promise<string> {
  const opinion = await prisma.opinion.findUnique({
    where: { disputeId },
    include: { dispute: { select: { title: true, category: true } } },
  });

  if (!opinion) {
    throw new NotFoundError('Opinion not found');
  }

  const contentStr = decrypt(opinion.encryptedContent, opinion.contentEncryptionKeyId);
  let content: any;
  try {
    content = JSON.parse(contentStr);
  } catch {
    throw new InternalError('Failed to parse opinion content');
  }

  const filename = `opinion_${disputeId.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
  const filePath = path.join(PDF_DIR, filename);

  if (!fs.existsSync(PDF_DIR)) {
    fs.mkdirSync(PDF_DIR, { recursive: true });
  }

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 50, right: 50 },
      info: {
        Title: `Opinion - ${opinion.dispute.title}`,
        Author: 'MeritView',
        Subject: 'Dispute Analysis Opinion',
      },
    });

    const stream = fs.createWriteStream(filePath);
    stream.on('finish', () => resolve(filename));
    stream.on('error', reject);

    doc.pipe(stream);

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    doc.font('Helvetica-Bold').fontSize(22).text('MeritView Opinion', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
      .text(`Generated: ${new Date().toISOString().split('T')[0]}`, { align: 'center' });
    doc.moveDown(1.5);

    doc.font('Helvetica-Bold').fontSize(16).fillColor('#000')
      .text(opinion.dispute.title, { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica').fillColor('#666')
      .text(`Category: ${opinion.dispute.category.replace(/_/g, ' ').toLowerCase()}`);
    doc.moveDown(0.5);

    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).strokeColor('#ccc').stroke();
    doc.moveDown(0.8);

    if (content.executiveSummary) {
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#000').text('Executive Summary');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10).fillColor('#333')
        .text(content.executiveSummary, {
          align: 'justify',
          lineGap: 4,
        });
      doc.moveDown(0.8);
    }

    if (content.analysis) {
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#000').text('Analysis');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10).fillColor('#333')
        .text(content.analysis, {
          align: 'justify',
          lineGap: 4,
        });
      doc.moveDown(0.8);
    }

    if (content.strengthAssessment) {
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#000').text('Strength Assessment');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10).fillColor('#333')
        .text(content.strengthAssessment, {
          align: 'justify',
          lineGap: 4,
        });
      doc.moveDown(0.8);
    }

    if (content.recommendation) {
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#000').text('Recommendation');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10).fillColor('#333')
        .text(content.recommendation, {
          align: 'justify',
          lineGap: 4,
        });
      doc.moveDown(0.8);
    }

    if (content.riskFactors) {
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#000').text('Risk Factors');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10).fillColor('#333')
        .text(content.riskFactors, {
          align: 'justify',
          lineGap: 4,
        });
      doc.moveDown(0.8);
    }

    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).strokeColor('#ccc').stroke();
    doc.moveDown(0.5);

    doc.fontSize(8).font('Helvetica').fillColor('#999')
      .text('This opinion was generated by MeritView AI analysis and is for informational purposes only. '
        + 'It does not constitute legal advice.', { align: 'center', lineGap: 2 });

    doc.end();
  });
}

export async function getOpinionPdfPath(disputeId: string): Promise<{ filePath: string; filename: string }> {
  const opinion = await prisma.opinion.findUnique({
    where: { disputeId },
    select: { pdfStorageKey: true },
  });

  if (!opinion) {
    throw new NotFoundError('Opinion not found');
  }

  if (!opinion.pdfStorageKey) {
    throw new NotFoundError('PDF not yet generated');
  }

  const filePath = path.join(PDF_DIR, opinion.pdfStorageKey);
  if (!fs.existsSync(filePath)) {
    throw new NotFoundError('PDF file not found on disk');
  }

  return { filePath, filename: opinion.pdfStorageKey };
}
