export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <h1 className="text-4xl font-bold text-gray-900 mb-6">Disclaimer</h1>

      <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-6 mb-8">
        <h2 className="text-xl font-bold text-yellow-800 mb-2">Important Notice</h2>
        <p className="text-yellow-800">
          MeritView provides AI-generated decision support and educational information only.
          It does NOT provide legal advice.
        </p>
      </div>

      <div className="prose prose-gray max-w-none space-y-6">
        <h2>No Attorney-Client Relationship</h2>
        <p>
          Use of MeritView does not create an attorney-client relationship. No attorney is reviewing
          your case. The opinions generated by our AI models are for informational and educational
          purposes only.
        </p>

        <h2>Not a Substitute for Legal Advice</h2>
        <p>
          The analysis provided by MeritView should not be relied upon as a substitute for
          professional legal advice from a qualified attorney licensed in your jurisdiction.
          Every legal situation is unique, and AI-generated analysis cannot account for all
          relevant facts, laws, and procedures.
        </p>

        <h2>No Guarantee of Outcomes</h2>
        <p>
          MeritView does not guarantee any specific outcomes or results. Our AI models provide
          analysis based on the information provided, but actual legal outcomes depend on many
          factors beyond the scope of our analysis.
        </p>

        <h2>For Informational Purposes Only</h2>
        <p>
          All content and opinions generated by MeritView are provided "as is" for informational
          purposes only. You should consult with a qualified attorney before making any decisions
          about your legal matter.
        </p>

        <h2>Jurisdictional Limitations</h2>
        <p>
          Laws vary by jurisdiction. Our analysis may not account for specific laws, regulations,
          or procedures applicable in your jurisdiction. Always consult a local attorney.
        </p>

        <h2>Contact</h2>
        <p>
          If you have questions about this disclaimer, please contact us at support@meritview.ai.
        </p>
      </div>
    </div>
  );
}
