export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <h1 className="text-4xl font-bold text-gray-900 mb-6">Legal Disclaimer</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: July 2026</p>

      <div className="bg-red-50 border border-red-200 rounded-xl p-6 mb-8">
        <h2 className="text-xl font-bold text-red-800 mb-2">Important Notice</h2>
        <p className="text-red-700 font-medium">
          MeritView provides AI-generated decision support and educational information only.
          It does NOT provide legal advice. Use of this service does not create an attorney-client relationship.
          Do not make legal decisions based solely on AI-generated analysis.
        </p>
      </div>

      <div className="prose prose-gray max-w-none space-y-6">
        <h2>1. No Attorney-Client Relationship</h2>
        <p>
          Use of MeritView, including submission of briefs, receipt of opinions, or any communication
          through the platform, does not create an attorney-client relationship between you and MeritView,
          its operators, employees, or affiliates. No attorney is reviewing your case. No confidential
          relationship, privilege, or duty of confidentiality exists under applicable law. Communications
          through the platform are not protected by attorney-client privilege or work product doctrine.
        </p>

        <h2>2. Not a Substitute for Professional Legal Advice</h2>
        <p>
          The analysis, opinions, and content provided by MeritView are generated by artificial intelligence
          models and are for informational and educational purposes only. They are not, and should not be
          construed as, legal advice, legal opinion, or legal guidance. Every legal situation is unique,
          and AI-generated analysis cannot account for all relevant facts, applicable laws, procedural
          rules, evidentiary standards, judicial precedents, or jurisdictional nuances. You should
          consult with a qualified attorney licensed to practice in your jurisdiction before taking any
          action based on the analysis provided.
        </p>

        <h2>3. No Guarantee of Accuracy or Completeness</h2>
        <p>
          MeritView does not guarantee the accuracy, completeness, reliability, or timeliness of any
          opinion generated by our AI models. AI models may produce inaccurate, biased, or incomplete
          analyses. The output depends on the quality and completeness of the information provided by
          users, and we cannot verify the factual accuracy of user submissions. Independent verification
          of all information and analysis is recommended. We expressly disclaim any liability for errors,
          omissions, or inaccuracies in AI-generated content.
        </p>

        <h2>4. No Guarantee of Outcomes</h2>
        <p>
          MeritView does not guarantee any specific outcomes, results, or resolutions. AI-generated
          opinions do not predict actual legal outcomes, which depend on numerous factors including
          but not limited to: the specific facts and circumstances, applicable laws and regulations,
          judicial discretion, evidentiary rulings, settlement dynamics, and the effectiveness of
          legal representation. Past performance of the Service does not predict future results.
        </p>

        <h2>5. For Informational and Educational Purposes Only</h2>
        <p>
          All content, opinions, analyses, and materials generated by MeritView are provided
          "as is" for informational and educational purposes only. They are not intended to create,
          and do not create, any enforceable rights or obligations. You should not rely on AI-generated
          analysis as a substitute for professional judgment. You assume all risks associated with
          using the Service.
        </p>

        <h2>6. Not a Binding Judgment or Arbitration Award</h2>
        <p>
          Opinions generated by MeritView do not constitute binding judgments, arbitration awards,
          mediation determinations, or any form of legally binding decision. They carry no legal
          force or effect. They do not constitute an offer of settlement, admission, or waiver of
          any legal rights. No party is obligated to accept or be bound by any opinion generated
          through the Service.
        </p>

        <h2>7. Jurisdictional Limitations</h2>
        <p>
          Laws, regulations, and legal standards vary significantly by jurisdiction. Our AI models
          may not be trained on or account for the specific laws, regulations, rules, or procedures
          applicable in your jurisdiction. Analysis that may be relevant in one jurisdiction may be
          incomplete, inaccurate, or misleading in another. Always consult a local attorney who is
          familiar with the laws and procedures in your specific jurisdiction.
        </p>

        <h2>8. No Warranties</h2>
        <p>
          MERITVIEW PROVIDES THE SERVICE ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES
          OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY. TO THE MAXIMUM EXTENT PERMITTED BY
          APPLICABLE LAW, MERITVIEW DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED
          WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
          MERITVIEW DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR
          FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS.
        </p>

        <h2>9. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL MERITVIEW, ITS
          OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT,
          INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO
          YOUR USE OF OR INABILITY TO USE THE SERVICE, INCLUDING BUT NOT LIMITED TO DAMAGES FOR
          LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, EVEN IF ADVISED OF THE
          POSSIBILITY OF SUCH DAMAGES. YOUR SOLE REMEDY IS TO DISCONTINUE USE OF THE SERVICE.
        </p>

        <h2>10. User Responsibility</h2>
        <p>
          You are solely responsible for: (a) verifying the accuracy of any information obtained
          through the Service; (b) consulting qualified professionals for advice specific to your
          situation; (c) making independent judgments and decisions regarding your legal matters;
          (d) ensuring compliance with all applicable laws and regulations; (e) protecting the
          confidentiality of your account and information. You assume all risk associated with the
          use of AI-generated analysis.
        </p>

        <h2>11. Third-Party AI Models</h2>
        <p>
          MeritView uses third-party AI models provided by Groq (Llama 3, Mixtral) and Google (Gemini)
          for evaluation and aggregation. These models are subject to their own limitations, biases,
          and terms of use. MeritView is not responsible for the performance, accuracy, or availability
          of third-party AI models. We make no representations about the suitability of these models
          for any particular purpose.
        </p>

        <h2>12. Future Changes</h2>
        <p>
          Our AI models, evaluation methodology, and aggregation techniques may change over time as
          technology evolves. Opinions generated at different times may not be directly comparable.
          We reserve the right to modify, update, or discontinue any aspect of the Service without
          prior notice. Continued use after changes constitutes acceptance of updated disclaimers.
        </p>

        <h2>13. Contact</h2>
        <p>
          If you have questions, concerns, or require clarification about this disclaimer, please
          contact us at legal@meritview.ai. We encourage you to print or save a copy of this
          disclaimer for your records.
        </p>
      </div>
    </div>
  );
}
